spring.datasource.url=jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# placeholders
biometria.endpoint=https://api.biometria.exemplo
biometria.apikey=COLOQUE_AQUI

twilio.sid=
twilio.token=

# springdoc
springdoc.api-docs.path=/v3/api-docs
